### ISSUE TITLE
数据预处理，为什么提示 ModuleNotFoundError: No module named 'data'

### ISSUE THREAD

**Issue by ananwjq** [DSXiangLi/ChineseNER#14]
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/113575763/190317348-4d0bb0ec-2d18-493a-9e54-665e8f3efd23.png">

**Comment by ananwjq** [comment]
设置PYTHONPATH解决

**Comment by wangxiajun68** [comment]
请问咋解决的，pythonpath在哪设置
