### ISSUE TITLE
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory ./pretrain_model/ch_google\bert_model.ckpt

### ISSUE THREAD

**Issue by 1357810la** [DSXiangLi/ChineseNER#15]

**Comment by 1357810la** [comment]
大家有没有遇到这个问题 啊

**Comment by 1357810la** [comment]
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\checkpoint_utils.py", line 97, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\checkpoint_utils.py", line 65, in load_checkpoint
    "given directory %s" % ckpt_dir_or_file)
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory ./pretrain_model/ch_google\bert_model.ckpt

**Comment by DSXiangLi** [comment]
@1357810la 预训练模型文件需要自行下载并复制到对应目录，这里需要下载google 的bert base模型文件并放到./pretrain_model/ch_google

**Comment by 1357810la** [comment]
> @1357810la 预训练模型文件需要自行下载并复制到对应目录，这里需要下载google 的bert base模型文件并放到./pretrain_model/ch_google

谢谢作者大大
