### ISSUE TITLE
关于bert下的数据增强

### ISSUE THREAD

**Issue by Skypow2012** [DSXiangLi/ChineseNER#19]
你好，我看people_daily_augment这里的图片记录，数据增强对于基于bert的模型，基本没有效果，是么？

**Comment by DSXiangLi** [comment]
大概率使用简单的数据增强对预训练模型的效果会比较有限，因为数据增强引入的额外文本信息，很大概率已经在与训练中被模型学到。不过如果是针对垂直领域例如金融，医疗，或者使用生成文本多样性更高的数据增强，可能也是会有一些效果的

**Comment by Skypow2012** [comment]
哦哦 学习了，感谢您的回复
