### ISSUE TITLE
请教如何加载保存的模型做推理

### ISSUE THREAD

**Issue by LingyvKong** [DSXiangLi/ChineseNER#2]
首先感谢作者分享的代码！
请问加载保存的模型是使用.restore()恢复吗，还是estimator有什么高级的API呢？希望可以得到作者指点orz

**Comment by DSXiangLi** [comment]
我是用estimator.export_saved_model保存模型，然后用tf.contrib.estimator.SavedModelEstimator直接返回estimator，之后就可以直接调用estimator.predict了。或者不做serving只是本地用的话，直接用tf.estimator.Estimator(warm_start_from='local_checkpint_dir')就可以加载本地训练好的checkpoint，直接用estimator.predict也成

**Comment by DSXiangLi** [comment]
@LingyvKong 新加了model export和serving的部分，serving_model有直接可以用的serving model，可以试下
