### ISSUE TITLE
你好，运行对应数据集preprocess.py，并没有生产对应的tfrecord和data_params，是哪里有问题吗

### ISSUE THREAD

**Issue by hypzz0627** [DSXiangLi/ChineseNER#3]
<img width="1440" alt="截屏2021-08-19 下午11 05 24" src="https://user-images.githubusercontent.com/37317281/130092920-ab99d178-0a99-421e-a62a-f91e314e44f5.png">

**Comment by ydwasd** [comment]
请问tfrecord和data_params是需要自己保存吗

**Comment by DSXiangLi** [comment]
@ydwasd 需要的，这里是处理好样本dump tfrecord，训练的时候读tfrecord的
