### ISSUE TITLE
1

### ISSUE THREAD

**Issue by tanglulu** [DSXiangLi/ChineseNER#4]
你好我在进行3运行单任务NER模型时输入的命令是"python main.py --model bert_bilstm_crf --data people_daily"
他出现了一个一直循环的warning如下：
WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 9 vs previous value: 9. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize.
请问是出了什么问题呢，该如何改进呢

**Comment by DSXiangLi** [comment]
@tanglulu 可以确认下你用的是bert_train_op么？里面我是显式把step+1写进train_op的
train_op = tf.group(train_op_list, [global_step.assign(global_step + 1)])

**Comment by tanglulu** [comment]
![image](https://user-images.githubusercontent.com/19523028/140597712-44017f19-ccb3-4154-a0b2-a6dad7aca5cc.png)
你好我觉得是不是我这里出了问题导致他无法停止，是我配置出了什么问题吗，tf是1.14.0的啊，谢谢

**Comment by tanglulu** [comment]
![image](https://user-images.githubusercontent.com/19523028/140598014-0a0eb384-d70b-4da5-adb5-bdc712e06ae2.png)
你好，是不是这里出了问题，我配置哪里不合适吗，tf是1.14.0啊，谢谢

**Comment by tanglulu** [comment]
![image](https://user-images.githubusercontent.com/19523028/140598014-0a0eb384-d70b-4da5-adb5-bdc712e06ae2.png)
你好，是不是这里出了问题，我配置哪里不合适吗，tf是1.14.0啊，谢谢

**Comment by DSXiangLi** [comment]
@tanglulu 这个问题在？如果是early stop的问题直接干掉试一下？

**Comment by DSXiangLi** [comment]
@tanglulu 哦我好像记得在哪里看到过，如果当前batch的loss是NAN这个batch会被跳过，于是会出现上述global_step没有增长的情况，不过看你的log global_step并不是被stuck在1而是在增长，可以完全跑完和我给pkl对比下模型效果

**Comment by tanglulu** [comment]
后面好像是编译器原因，之前那个不好意思我还没有找到原因。
我看到bert/optimization.py中的
![image](https://user-images.githubusercontent.com/19523028/140637647-fcb1cb1d-f7f5-4d4d-a438-8c43f4b70570.png)
我的操作就是将比如people_daily 进行process.py生成其分别的tfrecord和data_params后进行python main.py --model bert_crf --data people_daily我这样的操作完成后就会
![7381c3e7174c68704c296a59698eb97](https://user-images.githubusercontent.com/19523028/140637804-2a9f79b7-d920-448d-b588-d42f467fa5ed.png)
出现这样的warning且一直不结束我是哪里流程出了问题吗，不好意思，谢谢你

**Comment by tanglulu** [comment]
现在主要是有一个问题 我将epoch_size=1之后
![image](https://user-images.githubusercontent.com/19523028/140640382-9692ef27-4db1-4ec2-90ab-cad289b17fe2.png)
他就在/checkpoint下生成这几个文件之后不断更新  events.out.tfevents.1636278360.scs4450  不能走到下一步生成不了自己的.pkl 拿不到它的训练结果

**Comment by tanglulu** [comment]
而且就是这个warning每次就重复5遍就不再出现，但这时程序还在跑 我不知道什么问题
![image](https://user-images.githubusercontent.com/19523028/140640769-57bceaa3-77fd-4789-85ed-dc9cd2091e3b.png)

**Comment by DSXiangLi** [comment]
@tanglulu 大概率是loss不再是nan所以开始正常更新了，tensorboard看一下吧。我按你的参数跑并没看到这个warning

**Comment by tanglulu** [comment]
上面的问题已经解决了，最后麻烦问一下GPU加速是无法使用吗

**Comment by DSXiangLi** [comment]
@tanglulu 后来是啥问题？GPU能用呀，不是给了参数么?--gpu=1，然后有多卡的限定用哪些卡--device
