### ISSUE TITLE
维度的问题

### ISSUE THREAD

**Issue by GaoYb923** [DSXiangLi/ChineseNER#6]
运行“bilstm_softlexicon_cry”模型报错。
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[28,0,1] = 704369 is not in [0, 704369)
应该是词嵌入的向量长度问题，请问该改哪里

**Comment by DSXiangLi** [comment]
@GaoYb923 感谢捉虫，看着是有一次push带了个bug。在data.word_enhance里面的VocabModel，因为要在已有的词向量里面加入EOS，PAD这些补充字段，需要对预训练的embedding增加几行，vstack的时候shape不对。我刚刚改了，可以重新pull一下看看

**Comment by GaoYb923** [comment]
embedding的问题已解决。
感谢楼主分享！
